name: ALVIN MUFFLERS AND ACCESSORIES
favicon: null
layout_spectrum: 0.49067
typography_spectrum: 0.29743
title: ALVIN MUFFLERS AND ACCESSORIES
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0152a1'
    - '#ec1e22'
    - '#fdfdfd'
    - '#6594be'
    - '#f4756c'
  brandStrength: 0.875
  lightness: 0.75
  saturation: 0.625
  rhythmicContrast: 0.75
purpose: []
